name: Run packer build on a template file

on:
  push:
    branches:
        - 'main'


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    env:
      PACKER_VERSION: "1.10.0" # or: "latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."
        working-directory: ./packer

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
        working-directory: ./packer

      - name: Validate Packer Configuration
        run: packer validate .
        working-directory: ./packer

      - name: Build Machine Image with Packer
        run: packer build .
        working-directory: ./packer
